### ISSUE TITLE
GetPropertyLargeInteger tarkistus

### ISSUE THREAD

**Issue by pekkatki** [CommunityHiQ/Frends.Community.LDAP#9]
Huomattu että LDAP taskin palautuksesta haettaessa GetPropertyLargeInteger -metodilla, menneiden aikaleimojen konvertointi tuottaa isomman luvun kuin DateTime.MaxValue.Ticks: https://docs.microsoft.com/en-us/dotnet/api/system.datetime.maxvalue?view=netframework-4.8

 

Taskia olisi mielellään muokattava siten että päivämääräkenttiä pystyttäisi hakemaan päivämäärämuodossa ilman konversiota. Tällä kertaa oli kyseessä kenttä #result[0].GetPropertyLargeInteger("accountExpires")

 

Konversioasiaa on keskusteltu myös täällä: https://www.flowdock.com/app/hiq/frends/threads/DupSuZb8nuky5HY15ClCXXpwJY7

**Comment by RikuVirtanen** [comment]
Taskiin lisätty GetPropertyDateTime -metodi, joka palauttaa haetun property:n päivämäärämuodossa. Käytetään #result[0].GetPropertyDateTime(string <property>)
